import { generateData } from "./generator.js";
import { Cell } from "../cell.js";

export var dataStore: Record<string,unknown>;

export const fetchFromJson = async (key?:string) => {
    try{
        const response = await fetch("/data.json");
        if (!response.ok) throw new Error("File not found");
        dataStore = await response.json(); 
    }
    catch{
        console.log("data generated by method call");
        dataStore = generateData();
    }
    addToSheet(dataStore, key);

};
export function addToSheet(data: unknown, startKey: string = "0,0"): void {
    const [startRow = 0, startCol = 0] = startKey.split(',').map(Number);
    let currentRow = isNaN(startRow) ? 0 : startRow;
    const cell = new Cell();

    let records: unknown[] = [];
    if (Array.isArray(data)) {
        records = data;
    } else if (typeof data === 'object' && data !== null) {
        records = Object.values(data);
    }

    for (const item of records) {
        if (typeof item === 'object' && item !== null && !Array.isArray(item)) {
            const innerObject = item as Record<string, unknown>;
            let currentCol = isNaN(startCol) ? 0 : startCol;

            for (const innerKey of Object.keys(innerObject)) {
                const rawValue = innerObject[innerKey];
                
                let content = '';
                if (rawValue !== null && rawValue !== undefined) {
                    content = typeof rawValue === 'object' ? JSON.stringify(rawValue) : String(rawValue);
                }
                
                cell.bindTo(currentRow, currentCol).setRawValue(content);
                currentCol++;
            }
            currentRow++;
        }
    }
    console.log("Loaded data from json");
}